services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '80:80'
        environment:
            - VITE_API_BASE_URL=https://api.gpmailer.ru
            - VITE_COOKIE_DOMAIN=.gpmailer.ru
        restart: unless-stopped
